theme: jekyll-theme-minimal
title: Kavina Peters
description: Recent graduate with Bachelors in Environmental Economics and Policy from UC Berkeley 
## Navigation
- [Home](index.md)
- [CV](cv.md)
- [Research](research.md)
